export const ROUTES = {
  SPLASH: '/splash',
  LOGIN: '/login',
  HOME: '/',
  PAYMENTS: '/payments',
  PAYMENT_DETAILS: '/payments/:id',
  COMPLAINTS: '/complaints',
  COMPLAINT_NEW: '/complaints/new',
  COMPLAINT_DETAILS: '/complaints/:id',
  ANNOUNCEMENTS: '/announcements',
  ANNOUNCEMENT_DETAILS: '/announcements/:id',
  NOTIFICATIONS: '/notifications',
  SERVICES: '/services',
  MAINTENANCE: '/services/maintenance',
  VISITORS: '/services/visitors',
  FACILITIES: '/services/facilities',
  DOCUMENTS: '/services/documents',
  RULES: '/services/rules',
  CONTACT: '/services/contact',
  EMERGENCY: '/emergency',
  EMERGENCY_STATUS: '/emergency/status/:id',
  CHAT: '/chat',
  PROFILE: '/profile',
  UNIT: '/profile/unit',
  SETTINGS: '/profile/settings',
  SUPPORT: '/profile/support',
  FAQ: '/profile/faq',
} as const;
